// token.rs：Rust 版 Token/TokenType 定义与关键字表（与 Go 版 token.go 一致）。
use crate::diagnostic::Position;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenType {
    Illegal,
    Eof,
    Ident,
    Int,
    Float,
    String,
    Newline,
    Indent,
    Dedent,

    Def,
    Class,
    If,
    Elif,
    Else,
    For,
    While,
    Return,
    Raise,
    Try,
    Except,
    Finally,
    Pass,
    Break,
    Continue,
    Import,
    From,
    As,
    In,
    Not,
    And,
    Or,
    Is,
    None,
    True,
    False,
    Del,
    Assert,
    With,
    Yield,
    Global,
    Nonlocal,
    Lambda,
    Async,
    Await,

    Safe,
    Only,
    Lock,
    Mask,
    Cage,
    Guard,
    Seal,
    Trace,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    DoubleStar,
    FloorDiv,
    Shl,
    Shr,
    Amp,
    Pipe,
    Caret,
    Tilde,
    Lt,
    Gt,
    Le,
    Ge,
    EqEq,
    Ne,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    DoubleStarAssign,
    FloorDivAssign,
    ShlAssign,
    ShrAssign,
    AmpAssign,
    PipeAssign,
    CaretAssign,
    Colon,
    Comma,
    Dot,
    Semicolon,
    Arrow,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    At,
    Ellipsis,
}

pub fn keyword(name: &str) -> Option<TokenType> {
    Some(match name {
        "def" => TokenType::Def,
        "class" => TokenType::Class,
        "if" => TokenType::If,
        "elif" => TokenType::Elif,
        "else" => TokenType::Else,
        "for" => TokenType::For,
        "while" => TokenType::While,
        "return" => TokenType::Return,
        "raise" => TokenType::Raise,
        "try" => TokenType::Try,
        "except" => TokenType::Except,
        "finally" => TokenType::Finally,
        "pass" => TokenType::Pass,
        "break" => TokenType::Break,
        "continue" => TokenType::Continue,
        "import" => TokenType::Import,
        "from" => TokenType::From,
        "as" => TokenType::As,
        "in" => TokenType::In,
        "not" => TokenType::Not,
        "and" => TokenType::And,
        "or" => TokenType::Or,
        "is" => TokenType::Is,
        "None" => TokenType::None,
        "True" => TokenType::True,
        "False" => TokenType::False,
        "del" => TokenType::Del,
        "assert" => TokenType::Assert,
        "with" => TokenType::With,
        "yield" => TokenType::Yield,
        "global" => TokenType::Global,
        "nonlocal" => TokenType::Nonlocal,
        "lambda" => TokenType::Lambda,
        "async" => TokenType::Async,
        "await" => TokenType::Await,
        "safe" => TokenType::Safe,
        "only" => TokenType::Only,
        "lock" => TokenType::Lock,
        "mask" => TokenType::Mask,
        "cage" => TokenType::Cage,
        "guard" => TokenType::Guard,
        "seal" => TokenType::Seal,
        "trace" => TokenType::Trace,
        _ => return None,
    })
}

pub fn keyword_name(tt: TokenType) -> Option<&'static str> {
    Some(match tt {
        TokenType::Def => "def",
        TokenType::Class => "class",
        TokenType::If => "if",
        TokenType::Elif => "elif",
        TokenType::Else => "else",
        TokenType::For => "for",
        TokenType::While => "while",
        TokenType::Return => "return",
        TokenType::Raise => "raise",
        TokenType::Try => "try",
        TokenType::Except => "except",
        TokenType::Finally => "finally",
        TokenType::Pass => "pass",
        TokenType::Break => "break",
        TokenType::Continue => "continue",
        TokenType::Import => "import",
        TokenType::From => "from",
        TokenType::As => "as",
        TokenType::In => "in",
        TokenType::Not => "not",
        TokenType::And => "and",
        TokenType::Or => "or",
        TokenType::Is => "is",
        TokenType::None => "None",
        TokenType::True => "True",
        TokenType::False => "False",
        TokenType::Del => "del",
        TokenType::Assert => "assert",
        TokenType::With => "with",
        TokenType::Yield => "yield",
        TokenType::Global => "global",
        TokenType::Nonlocal => "nonlocal",
        TokenType::Lambda => "lambda",
        TokenType::Async => "async",
        TokenType::Await => "await",
        TokenType::Safe => "safe",
        TokenType::Only => "only",
        TokenType::Lock => "lock",
        TokenType::Mask => "mask",
        TokenType::Cage => "cage",
        TokenType::Guard => "guard",
        TokenType::Seal => "seal",
        TokenType::Trace => "trace",
        _ => return None,
    })
}

/// 与 Go 版 TokenType.String() 完全一致（关键字名/中文类别名/符号）。
pub fn name(tt: TokenType) -> String {
    if let Some(k) = keyword_name(tt) {
        return k.to_string();
    }
    match tt {
        TokenType::Illegal => "非法token".to_string(),
        TokenType::Eof => "EOF".to_string(),
        TokenType::Ident => "标识符".to_string(),
        TokenType::Int => "整数".to_string(),
        TokenType::Float => "浮点数".to_string(),
        TokenType::String => "字符串".to_string(),
        TokenType::Newline => "换行".to_string(),
        TokenType::Indent => "缩进".to_string(),
        TokenType::Dedent => "取消缩进".to_string(),
        TokenType::Plus => "+".to_string(),
        TokenType::Minus => "-".to_string(),
        TokenType::Star => "*".to_string(),
        TokenType::Slash => "/".to_string(),
        TokenType::Percent => "%".to_string(),
        TokenType::DoubleStar => "**".to_string(),
        TokenType::FloorDiv => "//".to_string(),
        TokenType::Shl => "<<".to_string(),
        TokenType::Shr => ">>".to_string(),
        TokenType::Amp => "&".to_string(),
        TokenType::Pipe => "|".to_string(),
        TokenType::Caret => "^".to_string(),
        TokenType::Tilde => "~".to_string(),
        TokenType::Lt => "<".to_string(),
        TokenType::Gt => ">".to_string(),
        TokenType::Le => "<=".to_string(),
        TokenType::Ge => ">=".to_string(),
        TokenType::EqEq => "==".to_string(),
        TokenType::Ne => "!=".to_string(),
        TokenType::Assign => "=".to_string(),
        TokenType::PlusAssign => "+=".to_string(),
        TokenType::MinusAssign => "-=".to_string(),
        TokenType::StarAssign => "*=".to_string(),
        TokenType::SlashAssign => "/=".to_string(),
        TokenType::PercentAssign => "%=".to_string(),
        TokenType::DoubleStarAssign => "**=".to_string(),
        TokenType::FloorDivAssign => "//=".to_string(),
        TokenType::ShlAssign => "<<=".to_string(),
        TokenType::ShrAssign => ">>=".to_string(),
        TokenType::AmpAssign => "&=".to_string(),
        TokenType::PipeAssign => "|=".to_string(),
        TokenType::CaretAssign => "^=".to_string(),
        TokenType::Colon => ":".to_string(),
        TokenType::Comma => ",".to_string(),
        TokenType::Dot => ".".to_string(),
        TokenType::Semicolon => ";".to_string(),
        TokenType::Arrow => "->".to_string(),
        TokenType::LParen => "(".to_string(),
        TokenType::RParen => ")".to_string(),
        TokenType::LBracket => "[".to_string(),
        TokenType::RBracket => "]".to_string(),
        TokenType::LBrace => "{".to_string(),
        TokenType::RBrace => "}".to_string(),
        TokenType::At => "@".to_string(),
        TokenType::Ellipsis => "...".to_string(),
        _ => "未知".to_string(),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub ty: TokenType,
    pub lit: String,
    pub line: u32,
    pub col: u32,
}

impl Token {
    pub fn pos(&self) -> Position {
        Position {
            line: self.line,
            col: self.col,
        }
    }
}
