// 由 tools/gen_errorinfo 从 internal/ast/errors.go 生成，勿手改。
// 错误码注册表：修改 Go 版后需重新生成（cargo test 有全码抽查）。

pub struct ErrorInfo {
    pub code: &'static str,
    pub title: &'static str,
    pub help: &'static str,
    pub note: &'static str,
    pub example: &'static str,
}

pub static ERROR_INFO: &[ErrorInfo] = &[
    ErrorInfo {
        code: "E0001",
        title: "语法不匹配",
        help: "检查该位置的期望符号，补全或修正语法结构",
        note: "docs/报错清单.md#E0001",
        example: "error[E0001]: 语法不匹配\n  --> example.fly:1:5\n   |\n   1 | x = (1 +\n   |     ^\n   |\n   = help: 期望 :，实际为 换行。补全表达式或语法符号",
    },
    ErrorInfo {
        code: "E0002",
        title: "期望表达式",
        help: "该位置需要一个表达式",
        note: "docs/报错清单.md#E0002",
        example: "error[E0002]: 期望表达式\n  --> example.fly:2:1\n   |\n   2 | x =\n   | ^\n   |\n   = help: 期望表达式，实际为 换行。在赋值号右侧补上表达式",
    },
    ErrorInfo {
        code: "E0003",
        title: "语句未正确结束",
        help: "检查语句结束符（换行/分号）与缩进",
        note: "docs/报错清单.md#E0003",
        example: "error[E0003]: 语句未正确结束\n  --> example.fly:1:7\n   |\n   1 | x = 1 2\n   |       ^\n   |\n   = help: 期望语句结束，实际为 数字字面量 2。移除多余内容或用分号/换行分隔",
    },
    ErrorInfo {
        code: "E0004",
        title: "关键字未实现",
        help: "替换为受支持的语法（如 with 改为 try/finally）",
        note: "docs/报错清单.md#E0004",
        example: "error[E0004]: 关键字未实现\n  --> example.fly:1:1\n   |\n   1 | with open(\"f\") as f:\n   | ^^^^\n   |\n   = help: 关键字 with 暂不支持。改用 try/finally 显式管理资源",
    },
    ErrorInfo {
        code: "E0005",
        title: "非法关键字参数名",
        help: "关键字参数名必须是标识符",
        note: "docs/报错清单.md#E0005",
        example: "error[E0005]: 非法关键字参数名\n  --> example.fly:1:8\n   |\n   1 | f(**1)\n   |        ^\n   |\n   = help: 关键字参数名必须是标识符。改为 f(x=1) 形式",
    },
    ErrorInfo {
        code: "E0006",
        title: "非法赋值目标",
        help: "赋值目标必须是变量、属性或下标表达式",
        note: "docs/报错清单.md#E0006",
        example: "error[E0006]: 非法赋值目标\n  --> example.fly:1:1\n   |\n   1 | 1 = x\n   | ^\n   |\n   = help: 非法赋值目标。等号左侧必须是可赋值的名字",
    },
    ErrorInfo {
        code: "E0007",
        title: "装饰器用法错误",
        help: "装饰器后必须跟随 def 或 class 定义",
        note: "docs/报错清单.md#E0007",
        example: "error[E0007]: 装饰器用法错误\n  --> example.fly:2:1\n   |\n   2 | @deco\n   | ^^^^^\n   |\n   = help: 装饰器后必须跟随 def 或 class。在 @deco 后定义函数或类",
    },
    ErrorInfo {
        code: "E0008",
        title: "推导式未支持",
        help: "改用循环逐项构建容器",
        note: "docs/报错清单.md#E0008",
        example: "error[E0008]: 推导式未支持\n  --> example.fly:1:1\n   |\n   1 | {k: v for k, v in d}\n   | ^^^^^^^^^^^^^^^^^^^^^^\n   |\n   = help: 字典/集合推导式暂不支持。改用 for 循环逐项构建容器",
    },
    ErrorInfo {
        code: "E0009",
        title: "字典解包未支持",
        help: "改用显式的 dict 合并表达式",
        note: "docs/报错清单.md#E0009",
        example: "error[E0009]: 字典解包未支持\n  --> example.fly:1:4\n   |\n   1 | {**d}\n   |    ^\n   |\n   = help: 字典解包 {} 暂不支持。改用显式的 dict 合并表达式",
    },
    ErrorInfo {
        code: "E0010",
        title: "lock 缺少变量名",
        help: "写法：lock 变量名 或 lock 变量名 = 值",
        note: "docs/报错清单.md#E0010",
        example: "error[E0010]: lock 缺少变量名\n  --> example.fly:1:5\n   |\n   1 | lock = 42\n   |     ^\n   |\n   = help: lock 需要一个变量名。写法：lock 变量名 或 lock 变量名 = 值",
    },
    ErrorInfo {
        code: "E0011",
        title: "seal 缺少 class",
        help: "seal 只能修饰 class 定义",
        note: "docs/报错清单.md#E0011",
        example: "error[E0011]: seal 缺少 class\n  --> example.fly:1:5\n   |\n   1 | seal def f():\n   |     ^^^\n   |\n   = help: seal 后必须跟随 class 定义。seal 只能修饰类",
    },
    ErrorInfo {
        code: "E0012",
        title: "trace 参数类型错误",
        help: "level 必须写为字符串，如 trace(level=\"WARN\"):",
        note: "docs/报错清单.md#E0012",
        example: "error[E0012]: trace 参数类型错误\n  --> example.fly:1:13\n   |\n   1 | trace(level=WARN):\n   |             ^^^^\n   |\n   = help: level 必须是字符串（如 \"WARN\"）。改为 trace(level=\"WARN\"):",
    },
    ErrorInfo {
        code: "E0013",
        title: "trace 参数类型错误",
        help: "args/ret 必须写为 True 或 False",
        note: "docs/报错清单.md#E0013",
        example: "error[E0013]: trace 参数类型错误\n  --> example.fly:1:13\n   |\n   1 | trace(args=1):\n   |             ^\n   |\n   = help: args 必须是 True 或 False。改为 trace(args=True):",
    },
    ErrorInfo {
        code: "E0014",
        title: "trace 参数类型错误",
        help: "args/ret 必须写为 True 或 False",
        note: "docs/报错清单.md#E0014",
        example: "error[E0014]: trace 参数类型错误\n  --> example.fly:1:11\n   |\n   1 | trace(ret=1):\n   |           ^\n   |\n   = help: ret 必须是 True 或 False。改为 trace(ret=True):",
    },
    ErrorInfo {
        code: "E0015",
        title: "未知 trace 参数",
        help: "仅支持 level/args/ret 三个参数",
        note: "docs/报错清单.md#E0015",
        example: "error[E0015]: 未知 trace 参数\n  --> example.fly:1:8\n   |\n   1 | trace(debug=True):\n   |        ^^^^^\n   |\n   = help: trace 参数 debug 未知（支持 level/args/ret）。删除或改名为支持的参数",
    },
    ErrorInfo {
        code: "E0016",
        title: "cage 参数类型错误",
        help: "cage 参数必须写为字符串，如 max_time=\"5s\"",
        note: "docs/报错清单.md#E0016",
        example: "error[E0016]: cage 参数类型错误\n  --> example.fly:1:11\n   |\n   1 | cage(max_time=5):\n   |           ^\n   |\n   = help: cage 参数 max_time 必须是字符串（如 max_time=\"5s\"）",
    },
    ErrorInfo {
        code: "E0017",
        title: "max_time 格式非法",
        help: "格式：500ms/5s/2m/1h",
        note: "docs/报错清单.md#E0017",
        example: "error[E0017]: max_time 格式非法\n  --> example.fly:1:12\n   |\n   1 | cage(max_time=\"5x\"):\n   |            ^^^^^\n   |\n   = help: max_time 格式非法：\"5x\"（支持 500ms/5s/2m/1h）。改为 max_time=\"5s\"",
    },
    ErrorInfo {
        code: "E0018",
        title: "max_memory 格式非法",
        help: "格式：64KB/100MB/2GB",
        note: "docs/报错清单.md#E0018",
        example: "error[E0018]: max_memory 格式非法\n  --> example.fly:1:14\n   |\n   1 | cage(max_memory=\"5\"):\n   |              ^^^\n   |\n   = help: max_memory 格式非法：\"5\"（支持 64KB/100MB/2GB）。改用带单位的写法",
    },
    ErrorInfo {
        code: "E0019",
        title: "未知 cage 参数",
        help: "仅支持 max_time/max_memory",
        note: "docs/报错清单.md#E0019",
        example: "error[E0019]: 未知 cage 参数\n  --> example.fly:1:8\n   |\n   1 | cage(max_cpu=\"1\"):\n   |        ^^^^^^^\n   |\n   = help: cage 参数 max_cpu 未知（支持 max_time/max_memory）",
    },
    ErrorInfo {
        code: "E0020",
        title: "cage 缺少限制",
        help: "至少指定 max_time 或 max_memory 之一",
        note: "docs/报错清单.md#E0020",
        example: "error[E0020]: cage 缺少限制\n  --> example.fly:1:5\n   |\n   1 | cage():\n   |     ^\n   |\n   = help: cage 需至少指定 max_time 或 max_memory 之一",
    },
    ErrorInfo {
        code: "E0021",
        title: "括号未闭合",
        help: "补全匹配的右括号 ) ] }",
        note: "docs/报错清单.md#E0021",
        example: "error[E0021]: 括号未闭合\n  --> example.fly:1:1\n   |\n   1 | x = (1 + 2\n   |     ^\n   |\n   = help: 未闭合的括号。补全右括号 )",
    },
    ErrorInfo {
        code: "E0022",
        title: "禁止制表符缩进",
        help: "将行首制表符替换为空格缩进",
        note: "docs/报错清单.md#E0022",
        example: "error[E0022]: 禁止制表符缩进\n  --> example.fly:2:1\n   |\n   2 | \\tx = 1\n   | ^\n   |\n   = help: 行首不支持制表符缩进。改用空格缩进",
    },
    ErrorInfo {
        code: "E0023",
        title: "缩进级别不一致",
        help: "检查并统一该块的空格缩进",
        note: "docs/报错清单.md#E0023",
        example: "error[E0023]: 缩进级别不一致\n  --> example.fly:3:1\n   |\n   3 |   pass\n   | ^\n   |\n   = help: 缩进级别与上层不一致。检查并统一该块的空格缩进",
    },
    ErrorInfo {
        code: "E0024",
        title: "字符串未闭合",
        help: "为字符串补上结束引号",
        note: "docs/报错清单.md#E0024",
        example: "error[E0024]: 字符串未闭合\n  --> example.fly:1:5\n   |\n   1 | x = \"abc\n   |     ^\n   |\n   = help: 字符串未闭合。为字符串补上结束引号",
    },
    ErrorInfo {
        code: "E0025",
        title: "数字字面量非法",
        help: "补全指数部分，如 1e5",
        note: "docs/报错清单.md#E0025",
        example: "error[E0025]: 数字字面量非法\n  --> example.fly:1:5\n   |\n   1 | x = 1e\n   |     ^^\n   |\n   = help: 指数部分缺少数字: 1e。补全指数部分，如 1e5",
    },
    ErrorInfo {
        code: "E0026",
        title: "数字字面量非法",
        help: "修正数字写法，如删除无效的前导零",
        note: "docs/报错清单.md#E0026",
        example: "error[E0026]: 数字字面量非法\n  --> example.fly:1:5\n   |\n   1 | x = 0123\n   |     ^^^^\n   |\n   = help: 非法数字字面量 0123。修正数字写法，如删除无效的前导零",
    },
    ErrorInfo {
        code: "E0027",
        title: "意外字符",
        help: "删除或替换该字符",
        note: "docs/报错清单.md#E0027",
        example: "error[E0027]: 意外字符\n  --> example.fly:1:3\n   |\n   1 | x = @\n   |     ^\n   |\n   = help: 意外的字符 '@'。删除或替换该字符",
    },
    ErrorInfo {
        code: "E0028",
        title: "多余的右括号",
        help: "删除多余的右括号",
        note: "docs/报错清单.md#E0028",
        example: "error[E0028]: 多余的右括号\n  --> example.fly:1:8\n   |\n   1 | x = (1))\n   |        ^\n   |\n   = help: 多余的右括号 ')'。删除多余的右括号",
    },
    ErrorInfo {
        code: "E0029",
        title: "名字重复定义",
        help: "删除或重命名其中一个定义",
        note: "docs/报错清单.md#E0029",
        example: "error[E0029]: 名字重复定义\n  --> example.fly:3:1\n   |\n   3 | def add():\n   | ^^^\n   |\n   = help: 名字 add 重复定义（第一次在第 1 行）。删除或重命名其中一个定义",
    },
    ErrorInfo {
        code: "E0030",
        title: "参数重复定义",
        help: "函数参数名必须唯一",
        note: "docs/报错清单.md#E0030",
        example: "error[E0030]: 参数重复定义\n  --> example.fly:1:7\n   |\n   1 | def f(a, a):\n   |       ^\n   |\n   = help: 函数参数 a 重复定义。函数参数名必须唯一",
    },
    ErrorInfo {
        code: "E0031",
        title: "污点数据流入危险汇点",
        help: "对该值先做净化（白名单/类型校验）再流入汇点，或改用 only 白名单约束",
        note: "SECURITY.md 污点分析一节",
        example: "error[E0031]: 污点数据流入危险汇点\n  --> example.fly:4:18\n   |\n   4 |     obj = pickle.loads(data)\n   |                  ^^^^^^\n   |\n   = help: 未净化的外部输入 data 流入 pickle.loads（危险汇点）。对该值先做净化（白名单/类型校验）再流入汇点，或改用 only 白名单约束",
    },
    ErrorInfo {
        code: "E0032",
        title: "敏感数据流入输出上下文",
        help: "对该值脱敏（如遮蔽/哈希）后再输出，或移除该输出调用",
        note: "SECURITY.md 污点分析一节",
        example: "error[E0032]: 敏感数据流入输出上下文\n  --> example.fly:5:5\n   |\n   5 |     print(token)\n   |     ^^^^^\n   |\n   = help: 敏感数据 token 不可流入 print（输出上下文）。对该值脱敏（如遮蔽/哈希）后再输出，或移除该输出调用",
    },
    ErrorInfo {
        code: "E0033",
        title: "lock 变量未定义",
        help: "先声明 lock 变量，或检查拼写",
        note: "docs/报错清单.md#E0033",
        example: "error[E0033]: lock 变量未定义\n  --> example.fly:2:5\n   |\n   2 | lock SECRET\n   |     ^^^^^^\n   |\n   = help: lock 变量 SECRET 未定义。先声明 lock 变量，或检查拼写",
    },
    ErrorInfo {
        code: "E0034",
        title: "lock 变量不可删除",
        help: "lock 变量生命周期受保护，删除将破坏不变量",
        note: "docs/报错清单.md#E0034",
        example: "error[E0034]: lock 变量不可删除\n  --> example.fly:2:5\n   |\n   2 | del SECRET\n   |     ^^^^^^\n   |\n   = help: lock 变量 SECRET 不可删除。lock 变量生命周期受保护",
    },
    ErrorInfo {
        code: "E0035",
        title: "lock 变量不可再赋值",
        help: "lock 变量只读；如需可变请改用普通变量",
        note: "docs/报错清单.md#E0035",
        example: "error[E0035]: lock 变量不可再赋值\n  --> example.fly:3:5\n   |\n   3 | SECRET = \"other\"\n   |     ^^^^^^\n   |\n   = help: lock 变量 SECRET 不可再赋值。lock 变量只读；如需可变请改用普通变量",
    },
    ErrorInfo {
        code: "E0036",
        title: "禁止反射修改 lock",
        help: "lock 变量不可通过反射（globals()[...]）修改",
        note: "docs/报错清单.md#E0036",
        example: "error[E0036]: 禁止反射修改 lock\n  --> example.fly:4:13\n   |\n   4 |     globals()[\"SECRET\"] = 1\n   |             ^^^^^^^^\n   |\n   = help: lock 变量 SECRET 不可通过反射修改。lock 变量不可通过反射（globals()[...]）修改",
    },
    ErrorInfo {
        code: "E0037",
        title: "禁止 setattr 修改 lock",
        help: "lock 变量不可通过 setattr 修改",
        note: "docs/报错清单.md#E0037",
        example: "error[E0037]: 禁止 setattr 修改 lock\n  --> example.fly:5:13\n   |\n   5 |     setattr(mod, \"SECRET\", 1)\n   |             ^^^^\n   |\n   = help: lock 变量 SECRET 不可通过 setattr 修改",
    },
    ErrorInfo {
        code: "E0038",
        title: "禁止反射读取 lock",
        help: "lock 变量不可通过反射（globals()/vars()/locals()）读取",
        note: "docs/报错清单.md#E0038",
        example: "error[E0038]: 禁止反射读取 lock\n  --> example.fly:1:1\n   |\n   1 | lock SECRET = \"abc\"\n   | ^^^^\n   |\n   = help: lock 变量 SECRET 不可通过 globals() 反射读取",
    },
    ErrorInfo {
        code: "E0039",
        title: "guard 变量未定义",
        help: "先定义该变量（或参数）再使用 guard",
        note: "docs/报错清单.md#E0039",
        example: "error[E0039]: guard 变量未定义\n  --> example.fly:2:5\n   |\n   2 |     guard age: int, 0 < age < 150\n   |     ^^^^^\n   |\n   = help: guard 变量 age 未定义。先定义该变量（或参数）再使用 guard",
    },
    ErrorInfo {
        code: "E0040",
        title: "guard 类型必须是简单类型名",
        help: "如 int、str、float、list、dict",
        note: "docs/报错清单.md#E0040",
        example: "error[E0040]: guard 类型必须是简单类型名\n  --> example.fly:2:12\n   |\n   2 | guard x: list[int]\n   |            ^^^\n   |\n   = help: guard 类型必须是简单类型名（如 int、str）。list[int] 请改写字面量条件",
    },
    ErrorInfo {
        code: "E0041",
        title: "guard 类型与注解不一致",
        help: "统一 guard 类型与参数注解的类型",
        note: "docs/报错清单.md#E0041",
        example: "error[E0041]: guard 类型与注解不一致\n  --> example.fly:2:8\n   |\n   2 | guard x: str  # 参数注解为 int\n   |        ^\n   |\n   = help: guard 类型 str 与参数注解 int 不一致。统一两者类型",
    },
    ErrorInfo {
        code: "E0042",
        title: "guard 缺少类型或条件",
        help: "至少指定一个类型或条件约束",
        note: "docs/报错清单.md#E0042",
        example: "error[E0042]: guard 缺少类型或条件\n  --> example.fly:2:5\n   |\n   2 | guard x:\n   |     ^\n   |\n   = help: guard 至少需要一个类型或条件。补充类型或条件约束",
    },
    ErrorInfo {
        code: "E0043",
        title: "guard 条件引用未定义名字",
        help: "先定义条件中引用的名字",
        note: "docs/报错清单.md#E0043",
        example: "error[E0043]: guard 条件引用未定义名字\n  --> example.fly:2:14\n   |\n   2 | guard x: 0 < x < limit\n   |              ^^^^^\n   |\n   = help: guard 条件中引用了未定义的名字 limit。先定义该名字",
    },
    ErrorInfo {
        code: "E0044",
        title: "only 白名单为空",
        help: "至少列出一个模块，如 only (json):",
        note: "docs/报错清单.md#E0044",
        example: "error[E0044]: only 白名单为空\n  --> example.fly:1:6\n   |\n   1 | only ():\n   |      ^\n   |\n   = help: only 白名单不能为空（需至少一个模块，如 only (json):）",
    },
    ErrorInfo {
        code: "E0045",
        title: "only 块外访问被禁止",
        help: "将该名字加入 only 白名单，或移除该访问",
        note: "docs/报错清单.md#E0045",
        example: "error[E0045]: only 块外访问被禁止\n  --> example.fly:2:9\n   |\n   2 |     os.system(\"rm -rf /\")\n   |         ^^^^^^\n   |\n   = help: only 块禁止访问 os（不在白名单 [json math]）。将该名字加入 only 白名单，或移除该访问",
    },
    ErrorInfo {
        code: "E0046",
        title: "seal 属性不可修改",
        help: "seal 类实例属性在实例化后不可再赋值",
        note: "docs/报错清单.md#E0046",
        example: "error[E0046]: seal 属性不可修改\n  --> example.fly:7:5\n   |\n   7 |     u.name = \"other\"\n   |     ^^^^^^\n   |\n   = help: seal 类实例 u 的属性 name 不可修改。seal 类实例属性在实例化后不可再赋值",
    },
    ErrorInfo {
        code: "E0047",
        title: "trace 级别非法",
        help: "使用 DEBUG/INFO/WARNING/ERROR/CRITICAL 之一",
        note: "docs/报错清单.md#E0047",
        example: "error[E0047]: trace 级别非法\n  --> example.fly:1:13\n   |\n   1 | trace(level=\"X\"):\n   |             ^\n   |\n   = help: trace 级别 X 非法（支持 DEBUG/INFO/WARNING/ERROR/CRITICAL）。改用其中之一",
    },
    ErrorInfo {
        code: "E0048",
        title: "保留前缀冲突",
        help: "函数名不能以 _fly_ 开头（运行时保留前缀）",
        note: "docs/报错清单.md#E0048",
        example: "error[E0048]: 保留前缀冲突\n  --> example.fly:2:5\n   |\n   2 |     def _fly_clean():\n   |     ^^^^^^^^^^^^^^^^\n   |\n   = help: trace 块内函数名 _fly_clean 不能以 _fly_ 开头（保留前缀）。改名去前缀",
    },
    ErrorInfo {
        code: "E0049",
        title: "保留前缀冲突",
        help: "参数名不能以 _fly_ 开头（运行时保留前缀）",
        note: "docs/报错清单.md#E0049",
        example: "error[E0049]: 保留前缀冲突\n  --> example.fly:2:12\n   |\n   2 |     def f(_fly_x):\n   |            ^^^^^\n   |\n   = help: trace 块内参数名 _fly_x 不能以 _fly_ 开头（保留前缀）。改名去前缀",
    },
    ErrorInfo {
        code: "E0050",
        title: "safe 变量未定义",
        help: "在 safe 声明前先赋值",
        note: "docs/报错清单.md#E0050",
        example: "error[E0050]: safe 变量未定义\n  --> example.fly:2:5\n   |\n   2 | safe name\n   |     ^^^^\n   |\n   = help: 未定义的名字 name（safe 需要先赋值）。在 safe 声明前先赋值",
    },
    ErrorInfo {
        code: "E0051",
        title: "mask 变量未定义",
        help: "在 mask 声明前先赋值",
        note: "docs/报错清单.md#E0051",
        example: "error[E0051]: mask 变量未定义\n  --> example.fly:2:5\n   |\n   2 | mask secret\n   |     ^^^^^^\n   |\n   = help: 未定义的名字 secret（mask 需要先赋值）。在 mask 声明前先赋值",
    },
    ErrorInfo {
        code: "E0052",
        title: "名字未定义",
        help: "先定义该名字，或检查拼写",
        note: "docs/报错清单.md#E0052",
        example: "error[E0052]: 名字未定义\n  --> example.fly:3:5\n   |\n   3 |     return result\n   |            ^^^^^^\n   |\n   = help: 未定义的名字 result。先定义该名字，或检查拼写",
    },
    ErrorInfo {
        code: "E0053",
        title: "参数个数不足",
        help: "补齐函数的必需参数",
        note: "docs/报错清单.md#E0053",
        example: "error[E0053]: 参数个数不足\n  --> example.fly:4:5\n   |\n   4 |     add(1)\n   |     ^^^^^^\n   |\n   = help: 函数 add 需要至少 2 个参数（实际 1 个）。补齐必需参数",
    },
    ErrorInfo {
        code: "E0054",
        title: "位置参数过多",
        help: "改用关键字参数传参",
        note: "docs/报错清单.md#E0054",
        example: "error[E0054]: 位置参数过多\n  --> example.fly:4:5\n   |\n   4 |     add(1, 2, 3)\n   |     ^^^^^^^^^^^^\n   |\n   = help: 函数 add 最多接受 2 个位置参数（实际 3 个）。改用关键字参数传参",
    },
    ErrorInfo {
        code: "E0055",
        title: "未知参数名",
        help: "检查参数名拼写",
        note: "docs/报错清单.md#E0055",
        example: "error[E0055]: 未知参数名\n  --> example.fly:4:9\n   |\n   4 |     add(1, x=2)\n   |         ^\n   |\n   = help: 函数 add 没有名为 x 的参数。检查参数名拼写",
    },
    ErrorInfo {
        code: "E0056",
        title: "参数重复传值",
        help: "同一参数只能传值一次",
        note: "docs/报错清单.md#E0056",
        example: "error[E0056]: 参数重复传值\n  --> example.fly:4:9\n   |\n   4 |     add(1, a=2)\n   |         ^\n   |\n   = help: 函数 add 参数 a 重复传值。同一参数只能传值一次",
    },
    ErrorInfo {
        code: "E0057",
        title: "常量表达式除零",
        help: "修正除数，避免除零",
        note: "docs/报错清单.md#E0057",
        example: "error[E0057]: 常量表达式除零\n  --> example.fly:1:5\n   |\n   1 | x = 10 // 0\n   |     ^^\n   |\n   = help: 常量表达式除数为零。修正除数，避免除零",
    },
    ErrorInfo {
        code: "E0058",
        title: "运算符类型不支持",
        help: "确保操作数类型匹配运算符",
        note: "docs/报错清单.md#E0058",
        example: "error[E0058]: 运算符类型不支持\n  --> example.fly:1:5\n   |\n   1 | x = \"a\" + 1\n   |     ^^^\n   |\n   = help: 运算符 + 不支持 str 与 int。确保操作数类型匹配运算符",
    },
    ErrorInfo {
        code: "E0059",
        title: "运算符类型不支持",
        help: "按位取反仅支持整数",
        note: "docs/报错清单.md#E0059",
        example: "error[E0059]: 运算符类型不支持\n  --> example.fly:1:5\n   |\n   1 | x = ~\"a\"\n   |     ^\n   |\n   = help: 运算符 ~ 不支持 str。按位取反仅支持整数",
    },
    ErrorInfo {
        code: "E0060",
        title: "运算符类型不支持",
        help: "确保操作数类型匹配运算符",
        note: "docs/报错清单.md#E0060",
        example: "error[E0060]: 运算符类型不支持\n  --> example.fly:1:5\n   |\n   1 | x = -\"a\"\n   |     ^\n   |\n   = help: 运算符 - 不支持 str。确保操作数类型匹配运算符",
    },
    ErrorInfo {
        code: "E0061",
        title: "in 右侧类型不支持",
        help: "in 右侧必须是可迭代容器",
        note: "docs/报错清单.md#E0061",
        example: "error[E0061]: in 右侧类型不支持\n  --> example.fly:1:7\n   |\n   1 | x = 1 in 42\n   |       ^^\n   |\n   = help: in 右侧不支持 int。in 右侧必须是可迭代容器",
    },
    ErrorInfo {
        code: "E0062",
        title: "类型不可下标访问",
        help: "仅列表/字典/字符串等容器支持下标",
        note: "docs/报错清单.md#E0062",
        example: "error[E0062]: 类型不可下标访问\n  --> example.fly:1:5\n   |\n   1 | x = 1[0]\n   |     ^\n   |\n   = help: int 不可下标访问。仅列表/字典/字符串等容器支持下标",
    },
    ErrorInfo {
        code: "E0063",
        title: "禁止调用危险内建",
        help: "eval/exec/open/getattr 等内建可直接逃逸沙箱，全部禁止调用",
        note: "docs/报错清单.md#E0063",
        example: "error[E0063]: 禁止调用危险内建\n  --> example.fly:1:1\n   |\n   1 | eval(user_input)\n   | ^^^^\n   |\n   = help: 禁止调用内建 eval（沙箱逃逸风险）。eval/exec/open/getattr 等内建可直接逃逸沙箱，全部禁止调用",
    },
    ErrorInfo {
        code: "E0064",
        title: "禁止反射访问",
        help: "__class__/__bases__/__subclasses__ 等反射链、模块属性（os/attrgetter/__builtins__ 及 _ 前缀私有属性）、异常帧 __traceback__、f-string 内联表达式可绕过沙箱，全部禁止访问",
        note: "docs/报错清单.md#E0064",
        example: "error[E0064]: 禁止反射访问\n  --> example.fly:1:9\n   |\n   1 | x = obj.__class__\n   |         ^^^^^^^^\n   |\n   = help: 禁止反射访问属性 __class__（沙箱逃逸风险）。__class__/__bases__/__subclasses__ 等反射链可绕过沙箱，禁止访问",
    },
    ErrorInfo {
        code: "E0065",
        title: "禁止访问 __builtins__",
        help: "__builtins__ 是沙箱内建代理的入口，直接访问即逃逸风险",
        note: "docs/报错清单.md#E0065",
        example: "error[E0065]: 禁止访问 __builtins__\n  --> example.fly:1:1\n   |\n   1 | __builtins__['eval']\n   | ^^^^^^^^^^^^\n   |\n   = help: 禁止访问 __builtins__（沙箱逃逸风险）。__builtins__ 是沙箱内建代理的入口，直接访问即逃逸风险",
    },
    ErrorInfo {
        code: "E0066",
        title: "禁止导入危险模块",
        help: "os/subprocess/sys/pickle 等模块可读写系统资源，禁止导入",
        note: "docs/报错清单.md#E0066",
        example: "error[E0066]: 禁止导入危险模块\n  --> example.fly:1:8\n   |\n   1 | import os\n   |        ^^\n   |\n   = help: 禁止导入危险模块 os（沙箱逃逸风险）。os/subprocess/sys/pickle 等模块可读写系统资源，禁止导入",
    },
];
