// lib.rs：Rust CLI 库入口——模块声明（lexer/ast/parser/checkd/format/errorcode/errorinfo）。
pub mod analyze;
pub mod ast;
pub mod checkd;
pub mod diagnostic;
pub mod errorcode;
pub mod fmt;
pub mod errorinfo;
pub mod format;
pub mod lexer;
pub mod parser;
pub mod gen;
pub mod help;
pub mod http;
pub mod json;
pub mod lsp;
pub mod typeinfer;
pub mod update;
pub mod version;
